Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2024-10, with the labels that each got.

#572 Member eligibility
  integrations/util/cache.py
  programs/co_county_zips.py
  programs/models.py
  programs/programs/calc.py
  programs/programs/co/basic_cash_assistance/calculator.py
  programs/programs/co/cash_back/calculator.py
  programs/programs/co/child_care_assistance/calculator.py
  programs/programs/co/connect_for_health/calculator.py
  programs/programs/co/dental_health_care_seniors/calculator.py
  programs/programs/co/denver_preschool_program/calculator.py
  programs/programs/co/denver_property_tax_relief/calculator.py
  programs/programs/co/denver_trash_rebate/calculator.py
  programs/programs/co/emergency_rental_assistance/calculator.py
  programs/programs/co/energy_assistance/calculator.py
  programs/programs/co/energy_resource_center/calculator.py
  programs/programs/co/every_day_eats/calculator.py
  programs/programs/co/every_day_eats/tests.py
  programs/programs/co/low_wage_covid_relief/calculator.py
  programs/programs/co/medicaid/adult_with_disability/calculator.py
  programs/programs/co/medicaid/child_with_disability/calculator.py
  programs/programs/co/medicaid/emergency/calculator.py
  programs/programs/co/medicaid/family_planning_services/calculator.py
  programs/programs/co/my_spark/calculator.py
  programs/programs/co/mydenver/calculator.py
  programs/programs/co/nfp/calculator.py
  programs/programs/co/nurse_family_partnership/calculator.py
  programs/programs/co/nurturing_futures/calculator.py
  programs/programs/co/omnisalud/calculator.py
  programs/programs/co/pe/member.py
  programs/programs/co/property_credit_rebate/calculator.py
  programs/programs/co/rental_assistance_grant/calculator.py
  programs/programs/co/reproductive_health_care/calculator.py
  programs/programs/co/rtdlive/calculator.py
  programs/programs/co/tabor/calculator.py
  programs/programs/co/trua/calculator.py
  programs/programs/co/universal_preschool/calculator.py
  programs/programs/co/utility_bill_pay/calculator.py
  programs/programs/co/weatherization_assistance/calculator.py
  programs/programs/federal/head_start/calculator.py
  programs/programs/federal/medicare_savings/calculator.py
  programs/programs/federal/pe/member.py
  programs/programs/federal/pe/spm.py
  programs/programs/federal/ssdi/calculator.py
  programs/programs/helpers.py
  programs/programs/nc/nc_aca/calculator.py
  programs/programs/policyengine/calculators/base.py
  programs/programs/policyengine/policy_engine.py
  screener/views.py
Labels: impact-high

#573 Fix new FPL year bug
  programs/models.py
Labels: bug, impact-low

#577 Calculated SSI income counted towards school meal income
  programs/programs/co/__init__.py
  programs/programs/co/every_day_eats/__init__.py
  programs/programs/co/every_day_eats/calculator.py
  programs/programs/co/pe/__init__.py
  programs/programs/co/pe/member.py
  programs/programs/federal/pe/__init__.py
  programs/programs/federal/pe/member.py
  programs/programs/federal/pe/spm.py
  programs/programs/policyengine/calculators/dependencies/__init__.py
  programs/programs/policyengine/calculators/dependencies/member.py
  programs/programs/policyengine/calculators/dependencies/spm.py
Labels: impact-medium

#586 Fix SNAP
  programs/programs/federal/pe/spm.py
  programs/programs/policyengine/calculators/dependencies/spm.py
Labels: impact-low

#585 Birth month and year
  screener/migrations/0085_householdmember_birth_year_month_and_more.py
  screener/models.py
  screener/serializers.py
  screener/views.py
Labels: impact-high, system-wide

#587 Refactor/expense options
  configuration/management/commands/add_config.py
  programs/programs/federal/pe/spm.py
  programs/programs/policyengine/calculators/dependencies/spm.py
Labels: impact-low

#590 Program Category
  programs/admin.py
  programs/migrations/0090_programcategory.py
  programs/migrations/0091_program_category_v2.py
  programs/migrations/0092_programcategory_icon.py
  programs/models.py
  programs/programs/calc.py
  programs/programs/categories/__init__.py
  programs/programs/categories/base.py
  programs/programs/categories/co/__init__.py
  programs/programs/categories/co/preschool.py
  programs/programs/federal/pe/spm.py
  screener/serializers.py
  screener/views.py
  translations/templates/base.html
  translations/templates/program_categories/filter.html
  translations/templates/program_categories/list.html
  translations/templates/program_categories/main.html
  translations/templates/program_categories/program_category.html
  translations/urls.py
  translations/views.py
Labels: impact-high, system-wide

#596 SNAP ineligible student
  programs/programs/federal/pe/spm.py
  programs/programs/helpers.py
  programs/programs/policyengine/calculators/dependencies/member.py
  programs/programs/warnings/__init__.py
  programs/programs/warnings/co/__init__.py
  programs/programs/warnings/co/snap_student.py
  screener/models.py
Labels: impact-medium, system-wide

#604 Count pregnant people as 2 for Medicaid and CHP+
  programs/programs/co/pe/member.py
  programs/programs/federal/pe/member.py
  programs/programs/policyengine/calculators/dependencies/member.py
Labels: impact-low, system-wide

#605 Update Utility Bill Pay
  programs/programs/co/utility_bill_pay/calculator.py
  programs/programs/helpers.py
  screener/views.py
Labels: impact-low

#600 Move test referrer to bottom of list, move dhs under jeffco
  configuration/management/commands/add_config.py
Labels: impact-low
