Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2024-04, with the labels that each got.

#312 Update RTD Live
  programs/programs/connect_for_health/calculator.py
  programs/programs/policyengine/calculators/dependencies/member.py
  programs/programs/rtdlive/calculator.py
  screener/models.py
Labels: impact-medium

#315 OmniSalud Amount
  programs/programs/__init__.py
  programs/programs/omnisalud/calculator.py
Labels: impact-medium

#305 Release 3/15/2024
  programs/programs/__init__.py
  programs/programs/connect_for_health/calculator.py
  programs/programs/connect_for_health/tax_credit_value.py
  programs/programs/omnisalud/calculator.py
  programs/programs/policyengine/calculators/dependencies/member.py
  programs/programs/rtdlive/calculator.py
  programs/programs/universal_preschool/calculator.py
  screener/models.py
Labels: impact-medium

#323 Fix Snap to be Yearly
  programs/programs/policyengine/calculators/programs/spm.py
Labels: bug, impact-medium

#326 Update Dependencies
  benefits/settings.py
  requirements.txt
Labels: impact-high

#317 Optional DB_HOST Variable
  benefits/settings.py
Labels: impact-low

#325 Add check branch GH workflow
  .github/workflows/enforcer.yaml
Labels: impact-low

#327 Colorado Emergency Rental Assistance Program (ERAP)
  programs/programs/co/__init__.py
  programs/programs/co/emergency_rental_assistance/__init__.py
  programs/programs/co/emergency_rental_assistance/calculator.py
  requirements.txt
Labels: impact-medium

#340 Automatically Email Screen
  authentication/views.py
  integrations/services/communications/__init__.py
  integrations/services/communications/cell.py
  integrations/services/communications/email.py
  integrations/services/communications/message.py
  screener/admin.py
  screener/migrations/0081_remove_message_cell_remove_message_email.py
  screener/models.py
  screener/views.py
Labels: impact-high
