Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2024-09, with the labels that each got.

#516 Feat/second tax unit
  programs/programs/co/pe/member.py
  programs/programs/co/rtdlive/calculator.py
  programs/programs/policyengine/calculators/base.py
  programs/programs/policyengine/calculators/constants.py
  programs/programs/policyengine/calculators/dependencies/base.py
  programs/programs/policyengine/calculators/dependencies/member.py
  programs/programs/policyengine/calculators/dependencies/tax.py
  programs/programs/policyengine/policy_engine.py
  screener/models.py
Labels: impact-high

#518 LEAP income limits spread sheet
  programs/programs/co/energy_assistance/calculator.py
Labels: impact-low

#519 Legal need language change
  configuration/management/commands/add_config.py
Labels: impact-low

#520 Refactor/cat benefits v2
  configuration/management/commands/add_config.py
Labels: impact-high

#522 Use head start counties from spread sheet
  programs/programs/federal/head_start/calculator.py
  programs/programs/federal/head_start/eligible_zipcodes.py
Labels: impact-medium

#524 Remove old warning message
  programs/admin.py
  programs/migrations/0087_remove_program_warning.py
  programs/models.py
  screener/serializers.py
  screener/views.py
  translations/templates/programs/list.html
  translations/templates/programs/program.html
Labels: impact-medium

#534 Fix Black GH Action
  .github/workflows/format.yaml
  programs/programs/__init__.py
  programs/programs/co/pe/member.py
  programs/programs/nc/__init__.py
  programs/programs/nc/pe/__init__.py
  programs/programs/nc/pe/member.py
  screener/models.py
Labels: impact-low

#550 Child SSDI is half of parent SSDI
  programs/programs/federal/ssdi/calculator.py
Labels: impact-low

#551 Cache the translations object
  integrations/util/cache.py
  translations/models.py
Labels: impact-medium

#554 Every Day Eats from PE
  programs/programs/co/__init__.py
  programs/programs/co/every_day_eats/__init__.py
  programs/programs/co/every_day_eats/calculator.py
  programs/programs/co/every_day_eats/tests.py
  programs/programs/co/pe/__init__.py
  programs/programs/co/pe/member.py
  programs/programs/federal/pe/__init__.py
  programs/programs/federal/pe/member.py
  programs/programs/policyengine/calculators/dependencies/member.py
Labels: impact-medium

#559 Exclude translations UML
  benefits/settings.py
Labels: impact-low
