Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2024-05, with the labels that each got.

#348 My Spark
  programs/programs/co/my_spark/calculator.py
Labels: impact-low

#349 Medicare Savings Income Limits
  programs/programs/federal/medicare_savings/calculator.py
Labels: impact-low

#350 CCCAP Bug Where Value Was 0
  programs/programs/co/child_care_assistance/calculator.py
Labels: impact-low

#353 Add State Code as a PE Dependent
  programs/programs/co/pe/member.py
  programs/programs/co/pe/tax.py
  programs/programs/nc/pe/member.py
  programs/programs/policyengine/calculators/dependencies/__init__.py
  programs/programs/policyengine/calculators/dependencies/base.py
  programs/programs/policyengine/calculators/dependencies/household.py
  programs/programs/policyengine/policy_engine.py
  screener/views.py
Labels: impact-high

#354 Override Estimated Value
  programs/migrations/0069_program_estimated_value.py
  programs/migrations/0070_auto_20240506_1817.py
  programs/migrations/0071_alter_program_estimated_value.py
  programs/models.py
  screener/serializers.py
  screener/views.py
  translations/templates/programs/program.html
  translations/templates/urgent_needs/urgent_need.html
Labels: impact-medium

#355 Nurse Family Partnership
  programs/programs/co/__init__.py
  programs/programs/co/nurse_family_partnership/__init__.py
  programs/programs/co/nurse_family_partnership/calculator.py
Labels: impact-medium

#356 Add Multiple Tax Units to API
  programs/models.py
  programs/programs/calc.py
  programs/programs/co/pe/member.py
  programs/programs/co/rtdlive/calculator.py
  programs/programs/federal/pe/member.py
  programs/programs/policyengine/calculators/base.py
  programs/programs/policyengine/policy_engine.py
  screener/models.py
  screener/serializers.py
  screener/views.py
Labels: impact-medium

#360 Update Programs That Depend on Medicaid Eligibility
  programs/programs/co/connect_for_health/calculator.py
  programs/programs/co/low_wage_covid_relief/calculator.py
  programs/programs/co/medicaid/adult_with_disability/calculator.py
  programs/programs/co/medicaid/child_with_disability/calculator.py
  programs/programs/co/medicaid/emergency/calculator.py
  programs/programs/co/medicaid/family_planning_services/calculator.py
  programs/programs/co/reproductive_health_care/calculator.py
  programs/programs/helpers.py
Labels: bug, impact-low

#377 Small Admin Improvements
  programs/models.py
  translations/bulk_import_translations.py
  translations/models.py
  translations/templates/programs/program.html
  translations/templates/urgent_needs/urgent_need.html
  translations/views.py
Labels: impact-high

#376 Add New Fields to HubSpot Upload
  authentication/views.py
  integrations/services/hubspot/integration.py
Labels: impact-high

#374 Programs List API
  programs/migrations/0072_program_website_description.py
  programs/migrations/0073_auto_20240521_1727.py
  programs/migrations/0074_alter_program_website_description.py
  programs/migrations/0075_urgentneed_website_description.py
  programs/migrations/0076_auto_20240521_2055.py
  programs/migrations/0077_alter_urgentneed_website_description.py
  programs/models.py
  programs/serializers.py
  programs/views.py
  screener/serializers.py
  translations/models.py
  translations/serializers.py
  translations/templates/programs/program.html
  translations/templates/urgent_needs/urgent_need.html
Labels: impact-low

#373 Add Private PE API
  integrations/util/cache.py
  programs/programs/co/pe/member.py
  programs/programs/co/pe/tax.py
  programs/programs/federal/pe/member.py
  programs/programs/federal/pe/spm.py
  programs/programs/policyengine/calculators/base.py
  programs/programs/policyengine/engines.py
  programs/programs/policyengine/policy_engine.py
Labels: impact-high

#370 Fix Medicaid Showing Results When Medicaid Insurance Selected
  screener/models.py
Labels: bug, impact-medium

#386 Add Script to Update User Info in HubSpot
  programs/programs/urgent_needs/urgent_need_functions.py
  screener/one_time_scripts.py
Labels: impact-high

#389 Add Denver Emergency Assistance
  programs/programs/urgent_needs/urgent_need_functions.py
  screener/views.py
Labels: impact-low

#388 Early Intervention Colorado
  programs/programs/urgent_needs/urgent_need_functions.py
  screener/views.py
Labels: impact-low

#392 SNAP Employment
  programs/programs/urgent_needs/urgent_need_functions.py
  screener/views.py
Labels: impact-high

#329 Bug/no results
  programs/management/commands/fpl_fix.py
  programs/management/commands/readd_programs.py
  programs/management/commands/remove_programs.py
Labels: ctd, nc specific
