Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2024-02, with the labels that each got.

#259 Updating property tax credit rebate income limits
  .gitignore
  programs/programs/property_credit_rebate/calculator.py
Labels: impact-low

#263 Switch Year Back to 2024
  programs/programs/policyengine/calculators/constants.py
Labels: impact-high

#264 Add Arabic to Languages
  benefits/settings.py
Labels: impact-medium

#258 Add Optional Query Param to Only Request One Lang
  translations/models.py
  translations/views.py
Labels: impact-medium

#265 Translation Import Command
  translations/bulk_import_translations.py
  translations/management/commands/bulk_import.py
  translations/templates/main.html
  translations/urls.py
  translations/views.py
Labels: impact-high

#266 Fix MySpark Bug for LGS
  programs/programs/my_spark/calculator.py
Labels: impact-low

#280 Release 1/16/2024
  programs/programs/head_start/calculator.py
  programs/programs/medicaid/family_planning_services/calculator.py
  screener/views.py
Labels: impact-high
