Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2024-11, with the labels that each got.

#606 update add_config script
  configuration/management/commands/add_config.py
Labels: impact-low

#609 Health check
  integrations/admin.py
  integrations/management/commands/health_check.py
  integrations/migrations/0001_squashed_0004_alter_link_link.py
  integrations/migrations/0005_link_status_code_alter_link_hash.py
  integrations/migrations/0006_link_valid_status_code.py
  integrations/migrations/0007_link_in_use.py
  integrations/models.py
  programs/models.py
  translations/models.py
  translations/views.py
Labels: impact-medium, system-wide

#614 Remove SNAP gross income test dependency
  programs/programs/federal/pe/spm.py
  programs/programs/policyengine/calculators/dependencies/spm.py
Labels: impact-low

#615 Fix Swagger docs
  programs/serializers.py
Labels: impact-low

#622 White label model
  configuration/migrations/0004_configuration_white_label.py
  configuration/migrations/0005_alter_configuration_white_label.py
  configuration/models.py
  integrations/migrations/0008_link_white_label.py
  integrations/migrations/0009_alter_link_white_label.py
  integrations/models.py
  programs/migrations/0095_county_white_label_document_white_label_and_more.py
  programs/migrations/0096_alter_county_white_label_alter_document_white_label_and_more.py
  programs/models.py
  screener/admin.py
  screener/migrations/0086_whitelabel_screen_white_label.py
  screener/migrations/0087_auto_20241105_2008.py
  screener/migrations/0088_alter_screen_white_label.py
  screener/models.py
  screener/serializers.py
Labels: impact-high, system-wide

#621 Fix Denver Trash Rebate
  programs/programs/co/denver_trash_rebate/calculator.py
Labels: impact-low

#612 Document Links
  programs/admin.py
  programs/migrations/0095_document_link.py
  programs/migrations/0096_document_link_defaults.py
  programs/migrations/0097_document_link_required.py
  programs/models.py
  screener/views.py
  translations/templates/documents/document.html
  translations/templates/documents/list.html
Labels: system-wide

#624 Feat/hubspot integration
  authentication/models.py
  authentication/views.py
  integrations/management/commands/hubspotsync.py
  integrations/services/cms_integration.py
  integrations/services/communications/message.py
  integrations/services/hubspot/__init__.py
  integrations/services/hubspot/integration.py
  screener/management/commands/email_new_benefits.py
Labels: system-wide

#641 Weatherization Assistance Program income limits
  programs/programs/co/weatherization_assistance/calculator.py
Labels: impact-low, benefit update

#643 Update OmniSalud income limits
  programs/programs/co/omnisalud/calculator.py
Labels: impact-low, benefit update

#649 SNAP for Success
  programs/programs/urgent_needs/urgent_need_functions.py
Labels: impact-low, benefit update
