Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2025-04, with the labels that each got.

#862 Duplicate validations in pull script
  screener/management/commands/pull_screens.py
Labels: impact-medium

#856 Updated NC consent to contact
  configuration/white_labels/nc.py
Labels: impact-low

#863 Add Pitkin county cobrand
  configuration/white_labels/co.py
Labels: impact-low

#864 Update should add to use explicit_tcpa_consent
  integrations/management/commands/hubspotsync.py
  integrations/services/cms_integration.py
Labels: impact-medium

#873 Fix pull_screens script when working with more rows
  screener/management/commands/pull_screens.py
Labels: impact-medium

#868 Fix the select state page
  configuration/management/commands/add_config.py
  configuration/white_labels/_default.py
Labels: impact-medium

#876 Energy: Add more help options to energy calculator
  configuration/white_labels/co_energy_calculator.py
  programs/programs/co/weatherization_assistance/calculator.py
Labels: impact-low

#877 Central: Bugfix/urgent need data controller
  programs/models.py
Labels: impact-low

#870 MA: Massachusetts programs
  configuration/white_labels/ma.py
  programs/admin.py
  programs/management/commands/white_label_template.py
  programs/programs/co/pe/member.py
  programs/programs/co/pe/spm.py
  programs/programs/co/pe/tax.py
  programs/programs/federal/pe/member.py
  programs/programs/federal/pe/spm.py
  programs/programs/federal/pe/tax.py
  programs/programs/ma/__init__.py
  programs/programs/ma/example_program/__init__.py
  programs/programs/ma/example_program/calculator.py
  programs/programs/ma/pe/__init__.py
  programs/programs/ma/pe/member.py
  programs/programs/ma/pe/spm.py
  programs/programs/ma/pe/tax.py
  programs/programs/nc/pe/member.py
  programs/programs/nc/pe/spm.py
  programs/programs/policyengine/calculators/__init__.py
  programs/programs/policyengine/calculators/base.py
  programs/programs/policyengine/calculators/dependencies/household.py
  programs/programs/policyengine/calculators/dependencies/member.py
  programs/programs/policyengine/calculators/dependencies/spm.py
  programs/programs/policyengine/calculators/dependencies/tax.py
  programs/templates/new_white_label/pe_program_member.py
  programs/urgent_needs/ma/__init__.py
  programs/urgent_needs/ma/example_urgent_need.py
  screener/migrations/0103_rename_has_ccfa_screen_has_ccdf.py
  screener/migrations/0104_rename_has_ma_macftc_screen_has_ma_macfc.py
  screener/migrations/0105_screen_needs_veteran_services.py
  screener/models.py
  screener/serializers.py
  screener/views.py
Labels: impact-high

#884 Energy: Remove Gilpin County CARE exclude county list
  programs/programs/co/energy_calculator/affordable_residential_energy/calculator.py
Labels: impact-low

#888 Central: Member caps
  programs/programs/categories/base.py
  screener/serializers.py
  screener/views.py
Labels: impact-medium

#879 Energy: AND-SO
  configuration/white_labels/co_energy_calculator.py
  programs/programs/co/energy_calculator/affordable_residential_energy/calculator.py
  screener/migrations/0103_screen_has_co_andso.py
  screener/migrations/0106_merge_20250414_2227.py
  screener/models.py
  screener/serializers.py
Labels: impact-low

#891 Energy: Energy EBT
  programs/programs/co/energy_calculator/__init__.py
  programs/programs/co/energy_calculator/energy_ebt/__init__.py
  programs/programs/co/energy_calculator/energy_ebt/calculator.py
Labels: impact-low

#898 MA: Add MA senior SNAP override and warning
  programs/programs/translation_overrides/__init__.py
  programs/programs/translation_overrides/ma.py
  programs/programs/warnings/__init__.py
  programs/programs/warnings/ma/__init__.py
  programs/programs/warnings/ma/senior_snap_application.py
Labels: impact-medium

#908 MA: Fixes
  configuration/white_labels/ma.py
  screener/migrations/0107_screen_has_aca.py
  screener/models.py
  screener/serializers.py
Labels: impact-low

#904 MA: CHIP
  programs/programs/federal/pe/member.py
  programs/programs/federal/pe/tax.py
  programs/programs/ma/pe/member.py
  programs/programs/policyengine/calculators/dependencies/member.py
Labels: impact-medium

#903 MA: State Supplement Program
  programs/programs/ma/pe/__init__.py
  programs/programs/ma/pe/member.py
  programs/programs/policyengine/calculators/dependencies/member.py
Labels: impact-low
