Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2025-01, with the labels that each got.

#673 Fix don't send to HubSpot for test screens
  integrations/services/cms_integration.py
Labels: impact-low

#674 Update SSDI value
  programs/programs/federal/ssdi/calculator.py
Labels: impact-low

#677 Warning message citizenship
  integrations/util/cache.py
  programs/admin.py
  programs/migrations/0100_warningmessage_legal_statuses.py
  programs/models.py
  screener/serializers.py
  screener/views.py
Labels: impact-medium, system-wide

#680 SNAP child support
  programs/programs/federal/pe/spm.py
  programs/programs/policyengine/calculators/dependencies/member.py
  programs/programs/policyengine/calculators/dependencies/spm.py
  validations/management/commands/validate.py
Labels: impact-medium, benefit update, system-wide

#678 TABOR
  programs/programs/co/tabor/calculator.py
Labels: impact-low, benefit update

#696 Remove FPL API request because it is broken
  programs/models.py
Labels: impact-low

#692 Exclude cash assistance from certain programs
  configuration/white_labels/co.py
  programs/programs/co/child_care_assistance/calculator.py
  programs/programs/co/connect_for_health/calculator.py
  programs/programs/co/medicaid/family_planning_services/calculator.py
  programs/programs/policyengine/calculators/dependencies/spm.py
  screener/models.py
Labels: impact-medium, system-wide

#691 Update the Weatherization Assistance Program to use new income limits spreadsheet
  programs/programs/co/weatherization_assistance/calculator.py
Labels: impact-medium

#709 Ignore frozen when pulling validations
  screener/serializers.py
  validations/management/commands/pull_validations.py
Labels: bug, impact-low, system-wide

#713 Don't add user to HubSpot in dev mode
  authentication/views.py
Labels: bug, impact-high

#705 Expose member eligibility
  programs/programs/calc.py
  programs/programs/policyengine/calculators/base.py
  screener/migrations/0091_householdmember_frontend_id.py
  screener/migrations/0092_auto_20250109_1721.py
  screener/models.py
  screener/serializers.py
  screener/views.py
Labels: impact-high, system-wide

#721 Fix webhook
  screener/migrations/0092_auto_20250109_1721.py
  screener/views.py
  translations/management/commands/bulk_translate.py
Labels: bug

#714 Add LIEAP Program to NC Screener
  configuration/white_labels/nc.py
  programs/programs/nc/__init__.py
  programs/programs/nc/nc_lieap/__init__.py
  programs/programs/nc/nc_lieap/calculator.py
  screener/migrations/0091_screen_has_nc_lieap.py
  screener/models.py
  screener/serializers.py
Labels: ctd, nc specific
