Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2025-02, with the labels that each got.

#736 Add NC Weatherization program to screener
  configuration/white_labels/nc.py
  programs/programs/nc/__init__.py
  programs/programs/nc/nc_weatherization/__init__.py
  programs/programs/nc/nc_weatherization/calculator.py
  screener/migrations/0094_screen_has_ncwap.py
  screener/models.py
  screener/serializers.py
Labels: ctd, nc specific

#739 Add energy programs
  configuration/white_labels/_default.py
  configuration/white_labels/base.py
  configuration/white_labels/co.py
  configuration/white_labels/co_energy_calculator.py
  configuration/white_labels/nc.py
  programs/admin.py
  programs/migrations/0101_program_required_programs.py
  programs/models.py
  programs/programs/co/__init__.py
  programs/programs/co/energy_assistance/calculator.py
  programs/programs/co/energy_calculator/__init__.py
  programs/programs/co/energy_calculator/affordable_residential_energy/__init__.py
  programs/programs/co/energy_calculator/affordable_residential_energy/calculator.py
  programs/programs/co/energy_calculator/electric_affordability_black_hills/__init__.py
  programs/programs/co/energy_calculator/electric_affordability_black_hills/calculator.py
  programs/programs/co/energy_calculator/electric_affordability_xcel/__init__.py
  programs/programs/co/energy_calculator/electric_affordability_xcel/calculator.py
  programs/programs/co/energy_calculator/emergency_assistance/__init__.py
  programs/programs/co/energy_calculator/emergency_assistance/calculator.py
  programs/programs/co/energy_calculator/energy_assistance/__init__.py
  programs/programs/co/energy_calculator/energy_assistance/calculator.py
  programs/programs/co/energy_calculator/energy_outreach/__init__.py
  programs/programs/co/energy_calculator/energy_outreach/calculator.py
  programs/programs/co/energy_calculator/energy_outreach_solar/__init__.py
  programs/programs/co/energy_calculator/energy_outreach_solar/calculator.py
  programs/programs/co/energy_calculator/gas_affordability_black_hills/__init__.py
  programs/programs/co/energy_calculator/gas_affordability_black_hills/calculator.py
  programs/programs/co/energy_calculator/gas_affordability_xcel/__init__.py
  programs/programs/co/energy_calculator/gas_affordability_xcel/calculator.py
  programs/programs/co/energy_calculator/natural_gas_bill_assistance/__init__.py
  programs/programs/co/energy_calculator/natural_gas_bill_assistance/calculator.py
  programs/programs/co/energy_calculator/percentage_of_income_payment_plan/__init__.py
  programs/programs/co/energy_calculator/percentage_of_income_payment_plan/calculator.py
  programs/programs/co/energy_calculator/property_credit_rebate/__init__.py
  programs/programs/co/energy_calculator/property_credit_rebate/calculator.py
  programs/programs/co/energy_calculator/utility_bill_pay/__init__.py
  programs/programs/co/energy_calculator/utility_bill_pay/calculator.py
  programs/programs/co/energy_calculator/weatherization_assistance/__init__.py
  programs/programs/co/energy_calculator/weatherization_assistance/calculator.py
  programs/programs/co/property_credit_rebate/calculator.py
  programs/programs/co/utility_bill_pay/calculator.py
  programs/programs/co/weatherization_assistance/calculator.py
  screener/models.py
  screener/serializers.py
  screener/views.py
Labels: impact-high

#745 Add gas providers to energy calculators
  configuration/white_labels/nc.py
  programs/models.py
  programs/programs/co/energy_calculator/__init__.py
  programs/programs/co/energy_calculator/affordable_residential_energy/calculator.py
  programs/programs/co/energy_calculator/electric_affordability_black_hills/calculator.py
  programs/programs/co/energy_calculator/electric_affordability_xcel/calculator.py
  programs/programs/co/energy_calculator/energy_outreach/calculator.py
  programs/programs/co/energy_calculator/energy_outreach_crisis_intervention/__init__.py
  programs/programs/co/energy_calculator/energy_outreach_crisis_intervention/calculator.py
  programs/programs/co/energy_calculator/gas_affordability_black_hills/calculator.py
  programs/programs/co/energy_calculator/gas_affordability_xcel/calculator.py
  programs/programs/co/energy_calculator/natural_gas_bill_assistance/calculator.py
  programs/programs/co/energy_calculator/percentage_of_income_payment_plan/calculator.py
  programs/programs/co/energy_calculator/utility_bill_pay/calculator.py
  programs/programs/co/energy_calculator/weatherization_assistance/calculator.py
  translations/bulk_import_translations.py
  translations/model_data.py
Labels: impact-medium

#752 [WIP] CTC fixes + some other random stuff
  configuration/white_labels/co.py
  programs/admin.py
  programs/programs/federal/pe/tax.py
  programs/programs/policyengine/calculators/base.py
  programs/programs/policyengine/calculators/constants.py
  programs/programs/policyengine/calculators/dependencies/tax.py
  programs/programs/policyengine/policy_engine.py
  screener/webhooks.py
Labels: impact-low

#750 Jeffco Public Schools config
  configuration/white_labels/co.py
Labels: impact-low

#757 New white label script
  .github/workflows/format.yaml
  Makefile
  programs/management/commands/white_label_template.py
  programs/programs/templates.py
  programs/programs/urgent_needs/__init__.py
  programs/programs/urgent_needs/base.py
  programs/programs/urgent_needs/co/__init__.py
  programs/programs/urgent_needs/co/bia_food_delivery.py
  programs/programs/urgent_needs/co/child_first.py
  programs/programs/urgent_needs/co/co_emergency_mortgage_assistance.py
  programs/programs/urgent_needs/co/co_legal_services.py
  programs/programs/urgent_needs/co/denver_emergency_assistance.py
  programs/programs/urgent_needs/co/diaper_banks.py
  programs/programs/urgent_needs/co/early_childhood_mental_health_support.py
  programs/programs/urgent_needs/co/early_intervention.py
  programs/programs/urgent_needs/co/eoc.py
  programs/programs/urgent_needs/co/foreclosure_fin_assist_program.py
  programs/programs/urgent_needs/co/helpkitchen_zipcode.py
  programs/programs/urgent_needs/co/meal_in_counties.py
  programs/programs/urgent_needs/co/parents_as_teacher.py
  programs/programs/urgent_needs/co/parents_of_preschool_youngsters.py
  programs/programs/urgent_needs/co/snap_employment.py
  programs/programs/urgent_needs/co/trua.py
  programs/programs/urgent_needs/co/util.py
  programs/programs/urgent_needs/urgent_need_functions.py
  programs/templates/new_white_label/config.py
  programs/templates/new_white_label/empty_init_file.py
  programs/templates/new_white_label/pe_program_init.py
  programs/templates/new_white_label/pe_program_member.py
  programs/templates/new_white_label/pe_program_spm.py
  programs/templates/new_white_label/pe_program_tax.py
  programs/templates/new_white_label/program.py
  programs/templates/new_white_label/program_init.py
  programs/templates/new_white_label/urgent_need.py
  programs/templates/new_white_label/urgent_need_init.py
  screener/views.py
  translations/models.py
Labels: impact-low, system-wide

#782 Fix Utility Bill Help
  programs/programs/co/energy_assistance/calculator.py
  programs/programs/co/energy_calculator/energy_assistance/calculator.py
  programs/programs/co/energy_calculator/utility_bill_pay/calculator.py
Labels: impact-low

#784 Powered by footer
  configuration/white_labels/co_energy_calculator.py
Labels: impact-medium

#790 Fix more energy calculator bugs
  programs/admin.py
  programs/programs/co/energy_calculator/affordable_residential_energy/calculator.py
  programs/programs/co/energy_calculator/energy_outreach/calculator.py
  programs/programs/co/energy_calculator/energy_outreach_solar/calculator.py
  translations/views.py
Labels: bug, impact-low

#769 Update TRUA income limits
  programs/programs/co/trua/calculator.py
  programs/programs/urgent_needs/co/trua.py
Labels: impact-low

#777 Retrigger webhook command
  configuration/white_labels/co_energy_calculator.py
  programs/management/commands/remove_programs.py
  programs/models.py
  screener/management/commands/retrigger_webhook.py
  screener/views.py
  screener/webhooks.py
Labels: impact-medium

#778 Filter out API key users in health_check command
  integrations/management/commands/health_check.py
Labels: impact-low, system-wide
