Repository Gary-Community-Ventures/benefits-api, pull requests merged in 2025-03, with the labels that each got.

#798 Use the correct CTC value
  programs/programs/federal/pe/tax.py
  programs/programs/policyengine/calculators/dependencies/tax.py
Labels: impact-medium

#799 Add state option to the configuration
  configuration/management/commands/add_config.py
  configuration/white_labels/base.py
  configuration/white_labels/co.py
  configuration/white_labels/co_energy_calculator.py
  configuration/white_labels/nc.py
  programs/templates/new_white_label/config.py
Labels: impact-medium

#812 Pull screens script
  benefits/settings.py
  programs/programs/policyengine/engines.py
  screener/management/commands/pull_screens.py
Labels: impact-high

#818 Add energy calculator warning for renters
  programs/programs/warnings/__init__.py
  programs/programs/warnings/co_energy_calculator/__init__.py
  programs/programs/warnings/co_energy_calculator/renters.py
Labels: impact-low

#824 Change referrer for no help flag on 211 to 211co
  configuration/white_labels/co.py
Labels: impact-low

#834 Energy Calculator Copy Edits
  configuration/management/commands/add_config.py
  configuration/white_labels/base.py
  configuration/white_labels/co.py
  configuration/white_labels/co_energy_calculator.py
  configuration/white_labels/nc.py
  programs/templates/new_white_label/config.py
Labels: impact-medium

#850 Remove tax dependent dependency from NC SCCA
  programs/programs/nc/pe/spm.py
Labels: impact-low

#838 Explicit TCPA consent
  authentication/migrations/0014_user_explicit_tcpa_consent_alter_user_tcpa_consent.py
  authentication/models.py
  authentication/serializers.py
  configuration/white_labels/base.py
  configuration/white_labels/co.py
  configuration/white_labels/nc.py
  integrations/services/cms_integration.py
  programs/templates/new_white_label/config.py
Labels: impact-high
